### PR TITLE
added working charge->refund_charge()

### PR DESCRIPTION
**Pull request by yahermann**

### CODE REVIEW

**Comment by yahermann** [comment]
Hi Rusty, added optional parameters: reason, refund_application_fee, and metadata.  i also added tests per your other message.  i also fixed a bug in Net::Stripe::Card -- the "type" parameter was changed to "brand" by Stripe and was failing some of the tests.  This is now fixed as well.

**Comment by rustyconover** [comment]
Just working on merging this... sorry for the delay.

**Comment by yahermann** [comment]
No worries.  Note that this pull request also fixes issue #39 
https://github.com/lukec/stripe-perl/issues/39

Also, I found another improvement I'd like to make.  I'd like to add support for Transfers.  Would you prefer if I add Transfers to this pull request, or do it separately?

**Comment by NacreData** [comment]
On 21 Jan 2015, at 17:34, yahermann wrote:

> No worries.  Note that this pull request also fixes issue #39
> https://github.com/lukec/stripe-perl/issues/39
>
> Also, I found another improvement I'd like to make.  I'd like to add 
> support for Transfers.  Would you prefer if I add Transfers to this 
> pull request, or do it separately?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/lukec/stripe-perl/pull/45#issuecomment-70882935

Separate issues probably best addressed in separate pull requests. 
Thanks for your work!


devin
--
contact info: http://nacredata.com/devin

Ask me about Google Apps for Work: hosting your domain-branded email, 
calendar and cloud storage on Google's infrastructure.

**Pull request merged**
