### PR TITLE
Mock the service if no API key exists

### PR DESCRIPTION
**Pull request by choroba**
Test at least the basic functionality even when the service isn't accessible.
(First 38 tests from `live.t` implemented. I originally had the first 112, but it was fragile, and there's no point in reimplementing Stripe again.)

### CODE REVIEW

**Comment by choroba** [comment]
Two new dependencies added to tests: `parent` and `Test::LWP::UserAgent`.

**Comment by choroba** [comment]
`parent` no longer needed.

**Comment by choroba** [comment]
http://blogs.perl.org/users/e_choroba/2016/01/post.html

**Comment by andrewsolomon** [comment]
@choroba thanks for putting in a huge effort - and an interesting article to boot! As of last week I've taken on the job of managing this package's CPAN releases and I promise that I'll run the end-to-end tests using my private key before accepting any pull requests.

On these grounds I'll say thanks, but no thanks because I think that it will be a lot of work to maintain this code as Stripe releases its new versions and its backward compatible changes (which it is still making to very old versions).

Thanks again,

Andrew

p.s If you'd still like to improve the testing on this package I'd feel more comfortable with extensive integration tests (tests against live).

Ideally this would be a test against each version of the API by putting the version in the header of the tests' requests https://stripe.com/docs/api#versioning

**Pull request closed without merging**
