### PR TITLE
Update version number

### PR DESCRIPTION
**Pull request by paultcochrane**
This now matches that displayed on MetaCPAN

### CODE REVIEW

**Comment by dolmen** [comment]
You could have as well completely removed the line as `first_version` is only for boostrapping Git::NextVersion. Once tags are there it is not necessary anymore.

**Comment by paultcochrane** [comment]
True, however the most recent tag is 0.13, which doesn't match any of the recent releases.  Perhaps tags should be added to the repo for the releases between then and now?

**Comment by dolmen** [comment]
Or maybe the tags are in the author local repo, but not here...

@rustyconover : `git push --tags`

**Comment by rustyconover** [comment]
Pushed

**Pull request merged**
