### PR TITLE
Updating tests to work based on discussion in #207

### PR DESCRIPTION
**Pull request by cjavilla-stripe**
These changes make tests pass for me. How's this look @sherrardb?

### CODE REVIEW

**Comment by sherrardb** [comment]
@cjavilla-stripe,
sorry, i missed your pull request while i was, well, preparing a pull request. :-) but i would prefer to merge your PR, for the sake of historical consistency.

please seem my comments on the commit.

thanks for pitching in.

**Comment by sherrardb** [comment]
@cjavilla-stripe, any update here?

**Comment by cjavilla-stripe** [comment]
Sorry getting pulled into some other work. :/

**Comment by sherrardb** [comment]
no worries

**Comment by sherrardb** [comment]
thanks @cjavilla-stripe for the pointers.

fixed with #209. closing.

**Pull request closed without merging**
